from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from .configuration import LauncherPaths
from .dependencies import resolve_npm_command


@dataclass(slots=True)
class WebRuntime:
    package_manager: str
    command: list[str]
    env: dict[str, str]


def detect_web_runtime(
    paths: LauncherPaths, host: str, port: int, api_url: str
) -> WebRuntime:
    package_manager = resolve_npm_command()
    env = dict(os.environ)
    env["HOST"] = host
    env["PORT"] = str(port)
    env["FL_API_BASE_URL"] = api_url
    env["NEXT_PUBLIC_FL_API_BASE_URL"] = api_url
    write_web_env_file(paths.web_dir, api_url)
    return WebRuntime(
        package_manager=package_manager,
        command=[
            package_manager,
            "run",
            "dev",
            "--",
            "--hostname",
            host,
            "--port",
            str(port),
        ],
        env=env,
    )


def write_web_env_file(web_dir: Path, api_url: str) -> None:
    env_file = web_dir / ".env.local"
    content = (
        "# Auto-generated by the platform launcher.\n"
        "# Keeps the Next.js frontend aligned with the active backend URL.\n"
        f"FL_API_BASE_URL={api_url}\n"
        f"NEXT_PUBLIC_FL_API_BASE_URL={api_url}\n"
    )
    env_file.write_text(content, encoding="utf-8")
