apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-worker
  namespace: fl-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-worker
  template:
    metadata:
      labels:
        app: python-worker
    spec:
      containers:
        - name: python-worker
          image: fl-platform/python-worker:milestone
          envFrom:
            - configMapRef:
                name: fl-platform-config
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
