// Unit coverage for capability_statement_verifier.cpp:
//  1. canonical_capability_payload_json against a byte-exact golden
//     vector produced by actually running
//     fl_platform.security.capability_statement's canonicalization
//     rule in Python (json.dumps(sort_keys=True, separators=(",",":"),
//     ensure_ascii=True)) -- see the comment on kGoldenPayloadJson
//     below for exactly how it was generated. This is what makes the
//     cross-language canonicalization claim (docs/canonical-security-
//     serialization.md) a tested fact rather than an assumption.
//  2. A real Ed25519 sign (via OpenSSL, standing in for what PyNaCl
//     does in capability_statement.py) + verify round trip, including
//     tamper and expiry rejection paths.
#include "fl_coordinator/capability_statement_verifier.hpp"
#include "worker/worker.pb.h"

#include <openssl/evp.h>

#include <array>
#include <cstdio>
#include <iostream>
#include <string>

namespace {

int g_failures = 0;

void check(bool condition, const std::string& label) {
    if (!condition) {
        std::cerr << "FAILED: " << label << "\n";
        ++g_failures;
    }
}

std::string hex_encode(const unsigned char* data, std::size_t length) {
    static constexpr char kHex[] = "0123456789abcdef";
    std::string out;
    out.reserve(length * 2);
    for (std::size_t i = 0; i < length; ++i) {
        out += kHex[(data[i] >> 4) & 0xF];
        out += kHex[data[i] & 0xF];
    }
    return out;
}

fl::worker::v1::SignedCapabilityStatement make_golden_payload() {
    fl::worker::v1::SignedCapabilityStatement statement;
    statement.set_schema_version(1);
    statement.set_worker_id("worker-1");
    statement.set_software_version("0.1.0");
    statement.set_build_id("build-1");
    statement.add_supported_algorithms("fedavg");
    statement.add_supported_privacy_modes("sample_level");
    statement.set_opacus_version("1.5.2");
    statement.set_secure_random_available(true);
    statement.add_supported_accountants("rdp");
    statement.add_supported_clipping_modes("fixed");
    statement.add_supported_models("mlp");
    statement.add_supported_model_schema_hashes("abc123");
    statement.set_maximum_task_bytes(1048576);
    statement.set_maximum_private_batch_size(256);
    statement.set_cpu_count(4);
    statement.set_gpu_available(false);
    statement.set_gpu_count(0);
    statement.set_issued_at(1785000000.123456);
    statement.set_expires_at(1785003600.0);
    statement.set_nonce("deadbeef");
    statement.set_signing_key_id("key-1");
    return statement;
}

// Generated by running, in this repository's own Python environment:
//   python -c "
//   import json
//   payload = {...same 21 fields as make_golden_payload() above...}
//   print(json.dumps(payload, sort_keys=True, separators=(',', ':'),
//                     ensure_ascii=True))"
// i.e. this is real Python output, not a hand-written guess at what
// Python would produce -- see this file's header comment.
constexpr const char* kGoldenPayloadJson =
    "{\"build_id\":\"build-1\",\"cpu_count\":4,\"expires_at\":1785003600.0,"
    "\"gpu_available\":false,\"gpu_count\":0,\"issued_at\":1785000000.123456,"
    "\"maximum_private_batch_size\":256,\"maximum_task_bytes\":1048576,"
    "\"nonce\":\"deadbeef\",\"opacus_version\":\"1.5.2\",\"schema_version\":1,"
    "\"secure_random_available\":true,\"signing_key_id\":\"key-1\","
    "\"software_version\":\"0.1.0\",\"supported_accountants\":[\"rdp\"],"
    "\"supported_algorithms\":[\"fedavg\"],\"supported_clipping_modes\":[\"fixed\"],"
    "\"supported_model_schema_hashes\":[\"abc123\"],\"supported_models\":[\"mlp\"],"
    "\"supported_privacy_modes\":[\"sample_level\"],\"worker_id\":\"worker-1\"}";

struct GeneratedKeypair {
    std::string public_key_hex;
    EVP_PKEY* pkey = nullptr;
};

GeneratedKeypair generate_ed25519_keypair() {
    GeneratedKeypair result;
    result.pkey = EVP_PKEY_Q_keygen(nullptr, nullptr, "ED25519");
    unsigned char raw_public[32];
    std::size_t raw_public_len = sizeof(raw_public);
    EVP_PKEY_get_raw_public_key(result.pkey, raw_public, &raw_public_len);
    result.public_key_hex = hex_encode(raw_public, raw_public_len);
    return result;
}

std::string sign_hex(EVP_PKEY* pkey, const std::string& message) {
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    EVP_DigestSignInit(ctx, nullptr, nullptr, nullptr, pkey);
    unsigned char signature[64];
    std::size_t signature_len = sizeof(signature);
    EVP_DigestSign(ctx, signature, &signature_len,
                   reinterpret_cast<const unsigned char*>(message.data()), message.size());
    EVP_MD_CTX_free(ctx);
    return hex_encode(signature, signature_len);
}

std::string sha256_hex_for_test(const std::string& message) {
    unsigned char digest[EVP_MAX_MD_SIZE];
    unsigned int digest_len = 0;
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    EVP_DigestInit_ex(ctx, EVP_sha256(), nullptr);
    EVP_DigestUpdate(ctx, message.data(), message.size());
    EVP_DigestFinal_ex(ctx, digest, &digest_len);
    EVP_MD_CTX_free(ctx);
    return hex_encode(digest, digest_len);
}

}  // namespace

int main() {
    using fl::coordinator::canonical_capability_payload_json;
    using fl::coordinator::verify_capability_statement;

    {
        const auto payload = make_golden_payload();
        const auto canonical = canonical_capability_payload_json(payload);
        check(canonical == kGoldenPayloadJson,
              "canonical_capability_payload_json byte-matches the real Python-produced "
              "golden vector");
    }

    {
        // Round-trip: sign the golden payload's canonical bytes with a
        // freshly generated Ed25519 key (via OpenSSL, standing in for
        // PyNaCl -- both are libsodium/OpenSSL-grade RFC 8032
        // implementations of the same algorithm) and confirm
        // verify_capability_statement accepts it.
        auto keypair = generate_ed25519_keypair();
        auto statement = make_golden_payload();
        const auto canonical = canonical_capability_payload_json(statement);
        statement.set_payload_hash(sha256_hex_for_test(canonical));
        statement.set_signature(sign_hex(keypair.pkey, canonical));
        statement.set_signing_public_key(keypair.public_key_hex);

        const auto result = verify_capability_statement(statement, /*now_unix_s=*/1785000100.0);
        check(result.valid, "a correctly signed, non-expired statement verifies as valid");
        check(result.reason == "ok", "a valid result carries reason \"ok\"");

        // Tamper with a signed field after signing -- payload_hash (and
        // therefore the signature, which covers the same bytes) must no
        // longer match.
        auto tampered = statement;
        tampered.set_cpu_count(999);
        const auto tampered_result =
            verify_capability_statement(tampered, /*now_unix_s=*/1785000100.0);
        check(!tampered_result.valid,
              "tampering with a signed field after signing is rejected");
        check(tampered_result.reason == "payload_hash does not match the payload",
              "tampering is specifically reported as a payload_hash mismatch");

        // Expired: now_unix_s past expires_at.
        const auto expired_result =
            verify_capability_statement(statement, /*now_unix_s=*/1785003700.0);
        check(!expired_result.valid, "an expired statement is rejected");
        check(expired_result.reason == "capability statement has expired",
              "expiry rejection carries the expected reason");

        // Wrong signing key: verify against a different keypair's
        // public key than the one that actually signed it.
        auto wrong_key_keypair = generate_ed25519_keypair();
        auto wrong_key_statement = statement;
        wrong_key_statement.set_signing_public_key(wrong_key_keypair.public_key_hex);
        const auto wrong_key_result =
            verify_capability_statement(wrong_key_statement, /*now_unix_s=*/1785000100.0);
        check(!wrong_key_result.valid,
              "verifying against the wrong public key is rejected");
        check(wrong_key_result.reason == "invalid signature",
              "wrong-key rejection is reported as an invalid signature");

        EVP_PKEY_free(keypair.pkey);
        EVP_PKEY_free(wrong_key_keypair.pkey);
    }

    {
        // expires_at left at 0 (never set) must be rejected even with an
        // otherwise-valid signature -- mirrors
        // sign_capability_statement's own Python-side refusal to sign
        // an unset expiry, but verify_capability_statement must not
        // trust an already-signed statement that somehow has one anyway.
        auto keypair = generate_ed25519_keypair();
        auto statement = make_golden_payload();
        statement.set_expires_at(0.0);
        const auto canonical = canonical_capability_payload_json(statement);
        statement.set_payload_hash(sha256_hex_for_test(canonical));
        statement.set_signature(sign_hex(keypair.pkey, canonical));
        statement.set_signing_public_key(keypair.public_key_hex);

        const auto result = verify_capability_statement(statement, /*now_unix_s=*/100.0);
        check(!result.valid, "a statement with expires_at left unset (0) is rejected");
        EVP_PKEY_free(keypair.pkey);
    }

    if (g_failures == 0) {
        std::cout << "all capability statement verifier tests passed\n";
    }
    return g_failures == 0 ? 0 : 1;
}
